#!/usr/bin/env ruby
require 'rubygems'
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", 'lib')))
require "bundler/setup"
require 'rdf/linter'
require 'getoptlong'
require 'open-uri'

output = STDOUT

opts = GetoptLong.new(
  ["--output", "-o", GetoptLong::REQUIRED_ARGUMENT]
)
opts.each do |opt, arg|
  case opt
  when '--output'         then output = File.open(arg, "w")
  end
end

RDF::Linter::Parser.cook_vocabularies(output)
