#!/usr/bin/env ruby
# Usage: gen_vocab url, prefix with --output and --location options
require 'rubygems'
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", 'lib')))
require "bundler/setup"
require 'rdf/linter'
require 'getoptlong'
require 'open-uri'

output = STDOUT

opts = GetoptLong.new(
  ["--location", "-l", GetoptLong::REQUIRED_ARGUMENT],
  ["--output", "-o", GetoptLong::REQUIRED_ARGUMENT]
)
options = {}

opts.each do |opt, arg|
  case opt
  when '--location'       then options[:location] = RDF::URI(arg)
  when '--output'         then options[:output] = File.open(arg, "w")
  end
end

RDF::Linter::Generate.new.vocab_def(RDF::URI(ARGV[0]), ARGV[1], options)
